name: amit_course
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.0-0.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  #icons
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.4.0

  #screen dynamic
  flutter_screenutil: ^5.6.0

  #providers riverpod
  flutter_riverpod: ^2.3.4
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6

  #search bar
  easy_search_bar: ^2.5.0
  #widgets
  custom_navigation_bar: ^0.8.2
  u_credit_card: ^1.0.3
  dash_flags: ^0.1.1



  flutter_beep:
  flutter_otp_text_field: ^1.1.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:

    - assets/resources/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
